---
- name: customize Parent Playbooks
  hosts: localhost

  tasks:
  - name: Set FQDN
    shell: uname -n | cut -c 9-13
    register : fqdn

  - name: Set IP for HANA1
    shell: nslookup hana-{{ fqdn.stdout }}1 |grep 192|cut -f 2 -d " "
    register : hana1ip

  - name: Set IP for HANA2
    shell: nslookup hana-{{ fqdn.stdout }}2 |grep 192|cut -f 2 -d " "
    register : hana2ip

  - name: Prepare hana1 in host_vars
    copy:
      src: /home/cloud-user/hanaworkshop-2023/temp/hana-xxxxx1
      dest: /home/cloud-user/hanaworkshop-2023/host_vars/hana-{{ fqdn.stdout }}1

  - name: Prepare hana2 in host_vars
    copy:
      src: /home/cloud-user/hanaworkshop-2023/temp/hana-xxxxx2
      dest: /home/cloud-user/hanaworkshop-2023/host_vars/hana-{{ fqdn.stdout }}2

  - name: Prepare hanas in group_vars
    template:
      src: /home/cloud-user/hanaworkshop-2023/temp/hanas
      dest: /home/cloud-user/hanaworkshop-2023/group_vars/hanas

  - name: Delete DEPRECATION WARNING
    lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: '^#deprecation_warnings = True'
      line: 'deprecation_warnings = False'

#  - name: Prepare hsr.yml
#    template:
#      src: /home/cloud-user/hanaworkshop-2023/temp/07_hsr.yml
#      dest: /home/cloud-user/hanaworkshop-2023/07_hsr.yml

#  - name: Prepare pacemaker.yml
#    template:
#      src: /home/cloud-user/hanaworkshop-2023/temp/08_pacemaker.yml
#      dest: /home/cloud-user/hanaworkshop-2023/08_pacemaker.yml

- name: Transfer and execute a script.
  hosts: sap

  tasks:
  - name: Transfer the script
    copy:
      src: /home/cloud-user/hanaworkshop-2023/pkg_fix.sh
      dest: /home/cloud-user
      mode: 0777

  - name: Execute the script
    command: sh /home/cloud-user/pkg_fix.sh

- name: Prepare media
  hosts: hanas

  tasks:
  - name: Copy install media
    copy:
      src_dir: /nfs/HANA_installation
      dest_dir: /tmp/media

  - name: Copy SAPCAR
    copy:
      src: /nfs/SAPCAR/SAPCAR_1311-80000935.EXE
      dest: /tmp/media
